//
// Module: CelestialEngine/Engine/Modules/Events
// File: KeyEvent.hpp
// Created by: Catalin Chirosca
// Created: 2026-02-16
// Updated by: Catalin Chirosca
// Updated: 2026-03-23
//

#pragma once

#ifndef CE_EVENTS_KEYEVENT_HPP
#define CE_EVENTS_KEYEVENT_HPP

#include "I_Event.hpp"

#include "Define/DynamicLinker.hpp"
#include "Define/Event.hpp"
#include "Types/KeyCode/KeyboardKeyCode.hpp"

#include <string>


/**
 * @namespace CE::Events
 * @brief Event system for handling input events, including keyboard and mouse events
 * @details Provides event classes for keyboard key presses, releases, and character typing.
 *			These events are generated by the input system when the user interacts with
 *			the keyboard. Each event contains relevant information such as key codes and
 *			repeat counts to allow for responsive input handling in the application.
 */
namespace CE::Events {

/**
 * @class I_KeyEvent
 * @brief Template base class for all keyboard events
 * @tparam T Type of the key code (int for key press/release, unsigned int for typed characters)
 * @details Abstract base class that provides common functionality for keyboard events.
 *			All keyboard events store a key code and belong to both the Keyboard and Input categories.
 */
template<typename T>
class I_KeyEvent: public I_Event {
public:
	/**
	 * @brief Gets the key code associated with this event
	 * @return T The key code (platform-specific)
	 */
	[[nodiscard]] T GetKeyCode() const { return _keyCode; }

	EVENT_CLASS_CATEGORY(EventCategoryKeyboard | EventCategoryInput)

protected:
	/**
	 * @brief Protected constructor
	 * @param keycode The key code for this event
	 * @details Only derived classes can construct a key event
	 */
	I_KeyEvent(T keycode): _keyCode(keycode) {}

protected:
	T _keyCode;										///< Key code
};

/**
 * @brief Type alias for keyboard key codes used in key events
 * @details This alias simplifies the type used for key codes in keyboard events, making it clear that these events are specifically related to keyboard input.
 *			It uses the KeyboardKeyCodes enum defined in the KeyCode namespace, which provides a standardized set of key codes across the application.
 */
using KeyType = KeyCode::KeyboardKeyCode;
using KeyCharType = KeyCode::KeyboardCharsCode;

/**
 * @class KeyPressedEvent
 * @brief Event triggered when a keyboard key is pressed
 * @details Contains the key code and repeat count. When a key is held down,
 *			this event may be generated multiple times with incrementing repeat counts.
 *			A repeat count of 0 indicates the initial press, values > 0 indicate repeats.
 */
class CE_API KeyPressedEvent: public I_KeyEvent<KeyType> {
public:
	/**
	 * @brief Constructor
	 * @param keycode Platform-specific key code of the pressed key
	 * @param repeatCount Number of times the key has repeated (0 for initial press)
	 * @details Creates a key pressed event with the specified key code and repeat count
	 */
	KeyPressedEvent(KeyType keycode, int repeatCount);

public:
	/**
	 * @brief Gets the repeat count for this key press
	 * @return int Repeat count (0 for initial press, >0 for repeats)
	 */
	[[nodiscard]] int GetRepeatCount() const { return _repeatCount; }

	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing key code and repeat count
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(KeyPressed)
private:
	int _repeatCount;								///< Number of times the key has repeated
};

/**
 * @class KeyReleasedEvent
 * @brief Event triggered when a keyboard key is released
 * @details Contains the key code of the released key. This event is generated
 *			when the user releases a previously pressed key.
 */
class CE_API KeyReleasedEvent: public I_KeyEvent<KeyType> {
public:
	/**
	 * @brief Constructor
	 * @param keycode Platform-specific key code of the released key
	 * @details Creates a key released event with the specified key code
	 */
	KeyReleasedEvent(KeyType keycode);

public:
	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing the key code
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(KeyReleased)
};

/**
 * @class KeyTypedEvent
 * @brief Event triggered when a character is typed
 * @details This event is used for text input and contains the Unicode code point
 *			of the typed character. Unlike KeyPressedEvent, this handles character
 *			input after keyboard layout processing and is suitable for text entry.
 */
class CE_API KeyTypedEvent: public I_KeyEvent<KeyCharType> {
public:
	/**
	 * @brief Constructor
	 * @param keycode Unicode code point of the typed character
	 * @details Creates a key typed event with the specified character code
	 */
	KeyTypedEvent(KeyCharType keycode);

public:
	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing the character code
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(KeyTyped)
};

}

#endif //CE_EVENTS_KEYEVENT_HPP
