//
// Module: CelestialEngine/Engine/Modules/Events
// File: MouseEvent.hpp
// Created by: Catalin Chirosca
// Created: 2026-02-16
// Updated by: Catalin Chirosca
// Updated: 2026-03-09
//

#pragma once

#ifndef CE_EVENTS_MOUSEEVENT_HPP
#define CE_EVENTS_MOUSEEVENT_HPP

#include "I_Event.hpp"

#include "Define/DynamicLinker.hpp"
#include "Define/Event.hpp"
#include "Types/KeyCode/MouseButtonCode.hpp"

#include <string>

/**
 * @namespace CE::Events
 * @brief Event system for handling mouse input events
 * @details Provides event classes for mouse movement, scrolling, and button presses/releases.
 *			These events are generated by the input system when the user interacts with the
 *			mouse. Each event contains relevant information such as cursor position, scroll
 *			offsets, and button codes to allow for responsive input handling in the application.
 */
namespace CE::Events {

/**
 * @class MouseMovedEvent
 * @brief Event triggered when the mouse cursor moves
 * @details Contains the new position of the mouse cursor in window coordinates.
 *			The origin (0, 0) is typically at the top-left corner of the window.
 */
class CE_API MouseMovedEvent final: public I_Event {
public:
	/**
	 * @brief Constructor
	 * @param x New X coordinate of the mouse cursor in window space
	 * @param y New Y coordinate of the mouse cursor in window space
	 * @details Creates a mouse moved event with the specified cursor position
	 */
	MouseMovedEvent(float x, float y);

	/**
	 * @brief Gets the X coordinate of the mouse cursor
	 * @return float X position in window coordinates
	 */
	[[nodiscard]] float GetX() const {return _x; }

	/**
	 * @brief Gets the Y coordinate of the mouse cursor
	 * @return float Y position in window coordinates
	 */
	[[nodiscard]] float GetY() const {return _y; }

	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing mouse coordinates
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(MouseMoved)
	EVENT_CLASS_CATEGORY(EventCategoryMouse | EventCategoryInput)

private:
	float _x, _y;									///< Mouse cursor position in window coordinates
};

/**
 * @class MouseScrolledEvent
 * @brief Event triggered when the mouse scroll wheel is moved
 * @details Contains the scroll offset in both X and Y directions. Most mice only
 *			have vertical scrolling (Y offset), but some devices support horizontal
 *			scrolling (X offset) as well.
 */
class CE_API MouseScrolledEvent final: public I_Event {
public:
	/**
	 * @brief Constructor
	 * @param xOffset Horizontal scroll offset (positive = right, negative = left)
	 * @param yOffset Vertical scroll offset (positive = up, negative = down)
	 * @details Creates a mouse scrolled event with the specified scroll offsets
	 */
	MouseScrolledEvent(float xOffset, float yOffset);

	/**
	 * @brief Gets the horizontal scroll offset
	 * @return float X scroll offset
	 */
	[[nodiscard]] float GetXOffset() const { return _xOffset; }

	/**
	 * @brief Gets the vertical scroll offset
	 * @return float Y scroll offset
	 */
	[[nodiscard]] float GetYOffset() const { return _yOffset; }

	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing scroll offsets
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(MouseScrolled)
	EVENT_CLASS_CATEGORY(EventCategoryMouse | EventCategoryInput)

private:
	float _xOffset, _yOffset;						///< Scroll wheel offsets
};

/**
 * @class I_MouseButtonEvent
 * @brief Base class for mouse button events
 * @details Abstract base class that provides common functionality for mouse button
 *			press and release events. Stores the button code and belongs to multiple
 *			mouse-related categories.
 */
class CE_API I_MouseButtonEvent: public I_Event {
public:
	/**
	 * @brief Gets the mouse button code
	 * @return int Platform-specific mouse button code (0=left, 1=right, 2=middle, etc.)
	 */
	[[nodiscard]] KeyCode::MouseButtonCode GetMouseButton() const { return _button; }

	EVENT_CLASS_CATEGORY(EventCategoryMouse | EventCategoryMouseButton | EventCategoryInput)

protected:
	/**
	 * @brief Protected constructor
	 * @param button Platform-specific mouse button code
	 * @details Only derived classes can construct a mouse button event
	 */
	I_MouseButtonEvent(KeyCode::MouseButtonCode button);

protected:
	KeyCode::MouseButtonCode _button;									///< Platform-specific mouse button code
};

/**
 * @class MouseButtonPressedEvent
 * @brief Event triggered when a mouse button is pressed
 * @details Contains the button code of the pressed button. Common button codes
 *			are 0 (left), 1 (right), 2 (middle), but additional buttons may be
 *			available depending on the hardware.
 */
class CE_API MouseButtonPressedEvent final: public I_MouseButtonEvent {
public:
	/**
	 * @brief Constructor
	 * @param button Platform-specific mouse button code
	 * @details Creates a mouse button pressed event with the specified button
	 */
	MouseButtonPressedEvent(KeyCode::MouseButtonCode button);

	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing the button code
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(MouseButtonPressed)
};

/**
 * @class MouseButtonReleasedEvent
 * @brief Event triggered when a mouse button is released
 * @details Contains the button code of the released button. This event is generated
 *			when the user releases a previously pressed mouse button.
 */
class CE_API MouseButtonReleasedEvent final: public I_MouseButtonEvent {
public:
	/**
	 * @brief Constructor
	 * @param button Platform-specific mouse button code
	 * @details Creates a mouse button released event with the specified button
	 */
	MouseButtonReleasedEvent(KeyCode::MouseButtonCode button);

	/**
	 * @brief Converts the event to a string representation
	 * @return std::string String containing the button code
	 */
	[[nodiscard]] std::string ToString() const override;

	EVENT_CLASS_TYPE(MouseButtonReleased)
};

}

#endif //CE_EVENTS_MOUSEEVENT_HPP
